name: Sync Bangumi to Notion

on:
  schedule:
    # 每天凌晨 2 点运行
    - cron: '0 18 * * *'
  workflow_dispatch:
    # 允许手动触发工作流

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 恢复缓存
      uses: actions/cache@v3
      with:
        path: .cache
        key: bgm-cache-${{ github.run_number }}
        restore-keys: |
          bgm-cache-
        
    - name: 运行同步脚本
      id: sync
      env:
        BGM_TOKEN: ${{ secrets.BGM_TOKEN }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        # 运行同步脚本
        python bgm_to_notion.py